In [2]:
import numpy as np

arr = np.arange(0,11)
arr[0:5] = 100   #broadcasting reassignment in numpy
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [5]:
arr = np.arange(0,11)
sliceOfArr = arr[0:5]  #slicing of array (if we do any changes in this array it will affect the original array)
sliceOfArr             #we can create a copy of array using arr.copy() method

array([0, 1, 2, 3, 4])

In [6]:
arr2D = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2D[0] #gives the entire first row
arr2D[1][1] #gives the result 25 (2nd row,2nd column) alternative arr2D[1,1]

np.int64(25)

In [7]:
#slicing of 2D array

In [8]:
arr2D = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [9]:
arr2D[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [10]:
arr2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [11]:
#conditional selection

In [13]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [15]:
boolArr = arr>4
boolArr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [16]:
arr[boolArr]

array([ 5,  6,  7,  8,  9, 10])