In [6]:
import numpy as np
mylist = [1,2,3]
newlist = np.array(mylist)  # this is how we can convert python array to numpy array
newlist

array([1, 2, 3])

In [7]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]
myMatrix
np.array(myMatrix)    #numpy will automatically detect that it is a 2D matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10) #this is how we can create array in numpy 
                #Syntax :- np.arange(startpoint,endpoint(not included),steps(optional))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros((2,5)) #how to create arrays of zeros
                #Syntax :- np.zeros((rows,columns))
                #similarly we can create arrays of ones
                #syntax :- np.ones((rows,columns))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.linspace(0,10,3) #how to create arrays with linear spacing between elements
                    #Syntax :- np.linspace(starpoint,endpoint(included),no of elements with linear spacing)
                    #this is different with np.arange 
                    #in np.arange we decide the space between the elements not the no. of elements
                    #in np.linspace we decide the no. of elements and the space between them is decided by the nympy itself

array([ 0.,  5., 10.])

In [13]:
np.eye(5) #how to create identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(5,2) #how to create a array of given shape and populate it with random values between 0-1(excluced)
                    #Syntax :- np.random.rand(rows,columns)

array([[0.68546817, 0.21891842],
       [0.6954986 , 0.50432831],
       [0.63225171, 0.1601571 ],
       [0.85832831, 0.49061854],
       [0.65812796, 0.80573053]])

In [18]:
np.random.randn(5,2)

array([[-1.53132673, -0.68066283],
       [-0.93361806, -1.20829731],
       [ 1.64736605,  0.70797482],
       [-1.48393859, -1.24579377],
       [-0.07852641,  0.10200344]])

In [19]:
np.random.randint(0,101,(4,5)) #gives an array of given shape with random values between 0-101
                               #Syntax :- np.random.randint(lowerThreshold,maxThreshold(exclusive),(rows,columns))

array([[ 49,  94,  60,  74,  98],
       [ 45,  99,  30,  56,  43],
       [ 14,  99,  99,  65,  35],
       [ 98,  66,   6, 100,  77]], dtype=int32)

In [22]:
np.random.seed(42)
np.random.rand(4)  #this will always generate same random number

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [24]:
arr = np.arange(25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr = np.random.randint(0,101,10)
ranarr
ranarr.max() #returns maximum value from array
ranarr.min() #returns minimum value from array
ranarr.argmax() #returns index of max value
ranarr.argmin() #returns index of min value
ranarr.dtype #returns data type of array

# we can get the shape of an array by using arr.shape attribute